project/app/src/main/java/com/iven/musicplayergo/MainActivity.java
project/app/src/main/res/values-fr/strings.xml
project/app/src/main/res/values-it/strings.xml
project/app/src/main/res/values-ru/strings.xml
project/app/src/main/res/values-ua/strings.xml
project/app/src/main/res/values/strings.xml

I added two new languages - Ukrainian and Russian and were added some changes (for the digital indication of the albums quantity) related to the plurals when different languages have different rules for grammatical agreement with quantity.

New translations and resolve "plurals"

---

project/app/src/main/res/values-de/strings.xml

Signed-off-by: Malte Kiefer <malte.kiefer@mailgermania.de>

added german tanslation

---

project/app/src/main/res/values-hi/strings.xml

Added Hindi localization folder values-hi

Added Hindi support

---

project/app/src/main/res/values-tr/strings.xml

Turkish strings updated

---

project/app/src/main/AndroidManifest.xml

Fix for issue [#99](https://github.com/enricocid/Music-Player-GO/issues/99)

Playback permission fix for Android Q

---

project/app/src/main/res/values-tr/strings.xml

I updated Turkish strings. If you saw wrong translate, let me know.
Best Regards,
Adem

Update Turkish translation

---

project/app/src/main/res/values-fr/strings.xml
project/app/src/main/res/values-in/strings.xml
project/app/src/main/res/values-it/strings.xml
project/app/src/main/res/values-nl/strings.xml
project/app/src/main/res/values-ru/strings.xml
project/app/src/main/res/values/strings.xml

I updated the French translation.
However I have a few questions before merging, that's why I am marking this as draft.
Is `&#160` used to create an unbreakable space?
I didn't find a proper way to translate this into French:
```xml
<string name="sorting_pref_ascending">Ascending</string>
<string name="sorting_pref_descending">Descending</string>
```
What do you think about this?
```xml
<string name="sorting_pref_ascending">A-Z</string>
<string name="sorting_pref_descending">Z-A</string>
```
Maybe it's better as a source too.
And for now I don't know what is the context of this string and I don't know how to translate it:
```xml
<string name="edge_pref_summary_on">Disable edge-to-edge</string>
<string name="edge_pref_summary_off">Enable edge-to-edge</string>
```
Could you please answer my …

Update French translation

---

project/app/src/main/res/values/styles.xml

[See](https://github.com/enricocid/Music-Player-GO/issues/104#issuecomment-573447828)

fixed blinking cursor

---

project/app/src/main/res/values-nl/strings.xml

Updated Dutch translation

---

project/app/src/main/res/values-fr/strings.xml

Update French translation (4.1.7)

---

project/app/src/main/res/values-tr/strings.xml

Turkish translation minor fix

---

project/app/src/main/java/com/iven/musicplayergo/MainActivity.kt
project/app/src/main/java/com/iven/musicplayergo/fragments/PreferencesFragment.kt
project/app/src/main/java/com/iven/musicplayergo/player/EqualizerUtils.kt
project/app/src/main/java/com/iven/musicplayergo/utils/Utils.kt

I was checking out this project and the project failed to compile because of some **unresolved reference**(multiple) issues. 
<br>
Please see the following screenshot for more details. 
<br>

[Fix] Unresolved string resource reference

---

project/app/src/main/res/values-es/strings.xml

refs: https://github.com/enricocid/Music-Player-GO/issues/114

Update Spanish translation

---

project/app/src/main/res/values-tr/strings.xml

Maybe i may have missed some strings. If you see, let me know. I'm sorry for delay.

Turkish strings updated.

---

project/app/src/main/res/values-ru/strings.xml

added missing localization for the values: sorting_pref, sorting_pref_track, sorting_pref_track_inv

added missing localization for the sorting strings

---

project/app/src/main/res/values-ru/strings.xml

added localizations for the : found_songs_pref_title, filter_pref_title, filter_popup_title, error_no_filter, repeat_loop_enabled, error_no_music, error_media_buttons, error_not_ready

added some missing russian translations

---

project/app/src/main/res/values-hi/strings.xml

added and updated to latest translation.

Updated values-hi/strings.xml

---

fastlane/metadata/android/in/changelogs/149.txt
fastlane/metadata/android/in/full_description.txt

Update Indonesian translations for PlayStore descriptions and changelogs

Update translations for PlayStore descriptions

---

fastlane/metadata/android/in/changelogs/151.txt

See: https://github.com/enricocid/Music-Player-GO/commit/454634d45706b4884d02377f9245b23fda486f2b

Translate changelog to Indonesian

---

project/app/src/main/res/values-bd/strings.xml
project/app/src/main/res/values-cn/strings.xml
project/app/src/main/res/values-eg/strings.xml
project/app/src/main/res/values-jp/strings.xml
project/app/src/main/res/values-lk/strings.xml
project/app/src/main/res/values-no/strings.xml
project/app/src/main/res/values-np/strings.xml
project/app/src/main/res/values-pk/strings.xml
project/app/src/main/res/values-th/strings.xml

hi ! this pull request  is for translations....
1. values-bd -> translation in bangle language ( Bangladesh )
2. values-cn -> translation in Chinese language ( China )
3. values-eg -> translation in Arabic language ( Egypt )
4. values-jp -> translation in Japanese language ( Japan )
5. values-np -> translation in Nepali language ( Nepal )

Translations

---

project/app/src/main/res/values-zh-rCN/strings.xml
project/app/src/main/res/values-zh-rTW/strings.xml

Chinese-Shimply & Chinese-Traditional Support
Translation

Chinese-Shimply & Chinese-Traditional Support

---

project/app/src/main/res/values-hi/strings.xml

updated strings

---

project/app/src/main/java/com/iven/musicplayergo/fragments/AllMusicFragment.kt
project/app/src/main/java/com/iven/musicplayergo/fragments/DetailsFragment.kt
project/app/src/main/java/com/iven/musicplayergo/fragments/PreferencesFragment.kt
project/app/src/main/java/com/iven/musicplayergo/ui/MainActivity.kt

Enable switching tab when with DetailsFragment or EquializerFragment open

---

project/app/src/main/java/com/iven/musicplayergo/player/MediaPlayerHolder.kt

fix audio focus no working on detailsFragment

---

project/app/src/main/java/com/iven/musicplayergo/fragments/PreferencesFragment.kt
project/app/src/main/java/com/iven/musicplayergo/ui/MainActivity.kt
project/app/src/main/java/com/iven/musicplayergo/ui/UIControlInterface.kt

reset volume on preciseVolume toggle

---

project/app/src/main/java/com/iven/musicplayergo/GoConstants.kt
project/app/src/main/java/com/iven/musicplayergo/MusicViewModel.kt
project/app/src/main/java/com/iven/musicplayergo/extensions/MusicExts.kt
project/app/src/main/java/com/iven/musicplayergo/fragments/AllMusicFragment.kt
project/app/src/main/java/com/iven/musicplayergo/fragments/MusicContainersListFragment.kt
project/app/src/main/java/com/iven/musicplayergo/helpers/ListsHelper.kt
project/app/src/main/java/com/iven/musicplayergo/models/Music.kt
project/app/src/main/res/menu/menu_music_search.xml
project/app/src/main/res/values/strings.xml

Sort by date added implementation.
This will resolve #231 
Thanks to @enricocid for infinite patience and help.

add date added sorting option

---

project/app/src/main/java/com/iven/musicplayergo/player/MediaPlayerHolder.kt

This successfully makes the app respond to intents launched from other applications. I tested this with my AI and it worked, but I'm not an expert in this domain so I can't say my solution is the "Best" solution but it definitely works.
Its possible there's something to be done with 
```
session.setFlags(
MediaSessionCompat.FLAG_HANDLES_MEDIA_BUTTONS or
MediaSessionCompat.FLAG_HANDLES_TRANSPORT_CONTROLS
)
```
as suggested here https://developer.android.com/guide/topics/media-apps/interacting-with-assistant but again my code works so good enough for me.
Note that this is not full AI support as I did not implement `ACTION_PLAY_FROM_SEARCH`, I only implemented stop, play, prev, next, toggle

Make the app respond to media button action intents

---

README.md

The app is beautiful, why the README.md shouldn't be? I love this icon and it is better not to hide it! Let it be recognizable.

Add Music-Player-GO icon on the top

---

fastlane/metadata/android/it/changelogs/114.txt
fastlane/metadata/android/it/changelogs/117.txt

It did work, and these are the last ones in /it.

More UTF-8 re-encoding
